### ISSUE TITLE
Small Typo in Docs.

### ISSUE THREAD

**Issue by jjames1011** [SoftwareBrothers/admin-bro-dev#20]
Not sure if this is the best place to report typos so sorry in advance if not! (I am a new user of admin bro and wasn't necessarily looking to contribute.)

Small typo in docs: https://adminbro.com/tutorial-passing-resources.html

![adminbro-typo](https://user-images.githubusercontent.com/23221402/94726162-b02d0580-0311-11eb-858e-29f80b7a9140.png)

[update]
here is another I noticed in the footer on home page https://adminbro.com/
<img width="267" alt="admin-bro-footer-typo" src="https://user-images.githubusercontent.com/23221402/96037613-ea6eca80-0e1a-11eb-8a1e-9b97b6dc3d1c.png">

**Comment by wojtek-krysiak** [comment]
it's perfect - thansk

**Comment by wojtek-krysiak** [comment]
took long but I've just fixed both of them with the release of v3.3. Thanks again for spotting that.
