### ISSUE TITLE
Having trouble configuring quill editor

### ISSUE THREAD

**Issue by jjames1011** [SoftwareBrothers/admin-bro-dev#21]
When I give a property option of 'type: richtext' and I try and pass along toolbar options: example: 

answer: {
      type: 'richtext',
      custom: {
        modules: {
          toolbar: [['bold', 'italic'], ['link', 'image']],        <--- These options do not seem to be getting through
        },
      },
    },

I am trying to add image functionality to the toolbar but its not working. 

It doesn't seem to be taking my quill custom options when compiling or bundling. The only way for me to get past this is to go into node_modules/admin-bro/lib/frontend/assets/scripts/app-bundle.development.js and edit this file directly to get the result that I want which does not seem ideal for production. 

I was wondering if maybe there is a way I need to rebundle admin bro or recompile somehow? I have tried uninstalling and reinstalling adminbro with npm and still having the issue.

 Any suggestions? Thanks!

**Comment by wojtek-krysiak** [comment]
closing as it duplicates https://github.com/SoftwareBrothers/admin-bro/issues/603
